import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import Sidebar from '@/components/Sidebar'
import RightSidebar from '@/components/RightSidebar'
import Header from '@/components/Header'

const montFont = localFont({
  src: [
    {
      path: '/fonts/mont/Mont-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/mont/Mont-Semibold.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '/fonts/mont/Mont-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-mont',
})

export const metadata: Metadata = {
  title: 'ZuAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={montFont.variable}>
        <Header />
        <div className='flex justify-between bg-[#E5ECF3] max-sm:mx-auto max-sm:items-center'>
          <Sidebar />
          {children}
          <RightSidebar />
        </div>
      </body>
    </html>
  )
}
